version: '3.8'

services:
  app:
    container_name: job-services
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: job-services:latest
    restart: always
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    environment:
      - DATABASE_URL=postgresql://admin:postgres@postgres:5432/mydb?schema=public
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
    networks:
      - kk-network

networks:
  kk-network:
    external: true