import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Layout/Sidebar";
import Topbar from "@/components/Layout/Topbar";
import { Toaster } from "@/components/ui/sonner";
import { CircleCheck } from "lucide-react";
import { Noto_Sans_Thai } from 'next/font/google'

const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto-sans-thai'
})

export const metadata: Metadata = {
    title: "KK || SERVICE",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="th" className={notoSansThai.variable}>
            <body className="flex h-screen w-screen flex-col overflow-hidden font-sans antialiased">
                <Topbar />
                <div className="flex grow overflow-hidden">
                    <Sidebar />
                    <main className="flex grow flex-col overflow-scroll bg-gray-50">
                        {children}
                    </main>
                </div>

                <Toaster
                    position="top-center"
                    icons={{
                        success: <CircleCheck />,
                    }}
                    toastOptions={{
                        className: "font-sans",
                        classNames: {
                            success: "toast_success",
                        },
                    }}
                />
            </body>
        </html>
    );
}
