import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { ToastContainer } from 'react-toastify';

const notoSansThai = Noto_Sans_Thai({
	subsets: ["latin", "thai"],
	weight: ["100", "200", "300", "400", "500", "600", "700"],
	variable: "--font-noto-sans-thai",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`antialiased ${notoSansThai.variable}`}>
				<Navbar />
				{children}
				<ToastContainer/>
			</body>
		</html>
	);
}
