import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import { ToastContainer } from "react-toastify";
import { Kanit } from "next/font/google";

import "./globals.css";

const kanit = Kanit({
	variable: "--font-kanit",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`antialiased ${kanit.variable}`}>
				<Navbar />
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
